import { Serie } from './serie.js';
export var series = [
    new Serie(1, "Los 100", "The CW", 7, "Un grupo de 100 jóvenes delincuentes es enviado a la Tierra desde una estación espacial para ver si el planeta es habitable tras un apocalipsis nuclear.", "https://www.netflix.com/title/70283261", "https://www.rottentomatoes.com/tv/the_100"),
    new Serie(2, "Percy Jackson y los Dioses del Olimpo", "Disney+", 1, "Basada en los libros de Rick Riordan, Percy Jackson descubre que es un semidiós y se embarca en una serie de aventuras con otros hijos de dioses griegos.", "https://www.disneyplus.com/series/percy-jackson-and-the-olympians", "https://www.rottentomatoes.com/tv/percy_jackson_and_the_olympians"),
    new Serie(3, "Grey's Anatomy", "ABC", 20, "Un grupo de cirujanos jóvenes navega por los desafíos personales y profesionales de la vida en el hospital Grey Sloan Memorial en Seattle.", "https://www.netflix.com/title/70140391", "https://www.rottentomatoes.com/tv/greys_anatomy"),
    new Serie(4, "The Walking Dead", "AMC", 11, "En un mundo devastado por un apocalipsis zombi, un grupo de supervivientes lucha por sobrevivir mientras se enfrenta a amenazas tanto humanas como zombis.", "https://www.amc.com/twdu/the-walking-dead", "https://www.rottentomatoes.com/tv/the_walking_dead"),
    new Serie(5, "Avatar: La leyenda de Aang", "Nickelodeon", 3, "Aang, el último maestro aire, debe aprender a controlar los cuatro elementos y detener a la Nación del Fuego para restaurar el equilibrio en el mundo.", "https://www.paramountplus.com/shows/avatar-the-last-airbender/", "https://www.rottentomatoes.com/tv/avatar_the_last_airbender"),
    new Serie(6, "Teen Wolf", "MTV", 6, "Un adolescente llamado Scott McCall se convierte en hombre lobo y debe equilibrar su nueva vida sobrenatural con las dificultades típicas de la adolescencia.", "https://www.paramountplus.com/shows/teen-wolf/", "https://www.rottentomatoes.com/tv/teen_wolf")
];
